import { Head, Link, router } from '@inertiajs/react';
import { useEffect, useState } from 'react';

export default function Index({ devices, filters }: any) {
    const [search, setSearch] = useState(filters?.search ?? '');
    useEffect(() => { const timer = setTimeout(() => router.get('/admin/devices', { search }, { preserveState: true, replace: true }), 500); return () => clearTimeout(timer); }, [search]);
    return <><Head title="Devices & SIMs" /><div className="main-content-container overflow-hidden" style={{ minHeight: '75vh' }}><div className="row"><div className="col-md-12"><div className="card bg-white rounded-10 border border-white mb-4">
        <div className="d-flex justify-content-between align-items-center flex-wrap gap-3 p-20"><div className="d-flex gap-3"><Link className="bg-transparent text-primary fs-16 border-0 p-0" href="/admin/devices/create">+ Add New Device</Link><Link className="bg-transparent text-primary fs-16 border-0 p-0" href="/admin/sims/create">+ Add New SIM</Link></div><div className="d-flex align-items-center gap-2 flex-wrap"><input className="form-control" style={{ width: '250px' }} value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search device, ID, or IMEI" /><button className="btn btn-primary text-white" onClick={() => router.get('/admin/devices', { search }, { preserveState: true, replace: true })}>Filter</button><button className="btn btn-secondary" onClick={() => { setSearch(''); router.get('/admin/devices'); }}>Reset</button></div></div>
        <div className="default-table-area mx-minus-1 table-to-do-list"><div className="table-responsive"><table className="table align-middle w-100"><thead><tr><th>Device ID</th><th>Device</th><th>Team</th><th>IMEI</th><th>SIMs</th><th>Status</th><th>Last Seen</th><th className="text-end">Action</th></tr></thead><tbody>{devices.data.length ? devices.data.map((device: any) => <tr key={device.id}><td>#{device.id}</td><td><div className="d-flex align-items-center"><div className="flex-shrink-0 rounded-circle bg-light-primary text-primary d-flex align-items-center justify-content-center" style={{ width: 35, height: 35 }}><i className="material-symbols-outlined fs-18">smartphone</i></div><div className="flex-grow-1 ms-12"><h4 className="fw-medium fs-16 mb-0">{device.name}</h4><small className="text-muted">{[device.manufacturer, device.model].filter(Boolean).join(' ') || 'Unknown device'}</small></div></div></td><td>{device.team?.team_name ?? '—'}</td><td>{device.imei ?? '—'}</td><td>{device.sims.length}</td><td><span className={`badge ${device.status === 'online' ? 'bg-success' : device.status === 'offline' ? 'bg-secondary' : 'bg-warning text-dark'}`}>{device.status}</span></td><td>{device.last_seen_at ? new Date(device.last_seen_at).toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' }) : 'Never'}</td><td><div className="d-flex justify-content-end" style={{ gap: '12px' }}><Link className="bg-transparent p-0 border-0 hover-text-success" href={`/admin/devices/${device.id}`}><i className="material-symbols-outlined fs-16 fw-normal text-body">visibility</i></Link></div></td></tr>) : <tr><td colSpan={8} className="text-center py-5">No devices found</td></tr>}</tbody></table></div><div className="d-flex justify-content-between align-items-center flex-wrap gap-3 pt-20 p-20"><span className="fs-14 text-muted">Showing {devices.data.length} devices</span><ul className="pagination mb-0">{devices.links?.map((link: any, index: number) => <li key={index} className={`page-item ${link.active ? 'active' : ''} ${!link.url ? 'disabled' : ''}`}><button className="page-link" disabled={!link.url} onClick={() => link.url && router.visit(link.url, { preserveState: true, preserveScroll: true })} dangerouslySetInnerHTML={{ __html: link.label }} /></li>)}</ul></div></div>
    </div></div></div></div></>;
}
