import { Head, Link, useForm } from '@inertiajs/react';
import Select from 'react-select';
import { toast } from 'sonner';

export default function Create({ teams = [], devices = [] }: any) {
    const { data, setData, post, processing, errors } = useForm({ team_id: '', device_id: '', slot_number: '1', phone_number: '', operator: '', country_code: '', subscription_id: '', sim_serial_number: '', carrier_name: '', status: 'active', is_enabled: true });
    const selectedTeam = teams.find((team: any) => String(team.id) === data.team_id);
    const selectedDevice = devices.find((device: any) => String(device.id) === data.device_id);
    const teamDevices = devices.filter((device: any) => String(device.team_id) === data.team_id);
    const submit = (event: React.FormEvent) => { event.preventDefault(); post('/admin/sims', { onError: (formErrors) => Object.values(formErrors).forEach((message) => toast.error(message)) }); };
    const selectStyle = { control: (base: any) => ({ ...base, minHeight: '45px', borderColor: '#e2e8f0' }) };

    return <><Head title="Add SIM" /><div className="row"><div className="col-lg-8"><div className="card bg-white p-20 rounded-10 border border-white mb-4"><h3 className="mb-20">Add SIM</h3><form onSubmit={submit}><div className="row">
        <div className="col-md-6 mb-20"><label className="label fs-16 mb-2">Team</label><Select isClearable options={teams.map((team: any) => ({ value: String(team.id), label: team.team_name }))} value={selectedTeam ? { value: data.team_id, label: selectedTeam.team_name } : null} onChange={(option) => { setData('team_id', option?.value ?? ''); setData('device_id', ''); }} placeholder="Select Team" styles={selectStyle} />{errors.team_id && <div className="text-danger mt-1">{errors.team_id}</div>}</div>
        <div className="col-md-6 mb-20"><label className="label fs-16 mb-2">Device</label><Select isClearable isDisabled={!data.team_id} options={teamDevices.map((device: any) => ({ value: String(device.id), label: `${device.name} (${device.device_id})` }))} value={selectedDevice ? { value: data.device_id, label: `${selectedDevice.name} (${selectedDevice.device_id})` } : null} onChange={(option) => setData('device_id', option?.value ?? '')} placeholder={data.team_id ? 'Select Device' : 'Select a team first'} styles={selectStyle} />{errors.device_id && <div className="text-danger mt-1">{errors.device_id}</div>}</div>
        <div className="col-md-4 mb-20"><label className="label fs-16 mb-2">SIM Slot</label><input required min="1" type="number" className="form-control" value={data.slot_number} onChange={(event) => setData('slot_number', event.target.value)} />{errors.slot_number && <div className="text-danger mt-1">{errors.slot_number}</div>}</div>
        <div className="col-md-8 mb-20"><label className="label fs-16 mb-2">Phone Number</label><input className="form-control" value={data.phone_number} onChange={(event) => setData('phone_number', event.target.value)} placeholder="e.g. +8801XXXXXXXXX" /></div>
        <div className="col-md-6 mb-20"><label className="label fs-16 mb-2">Operator</label><input className="form-control" value={data.operator} onChange={(event) => setData('operator', event.target.value)} placeholder="e.g. Grameenphone" /></div><div className="col-md-6 mb-20"><label className="label fs-16 mb-2">Country Code</label><input className="form-control" value={data.country_code} onChange={(event) => setData('country_code', event.target.value)} placeholder="e.g. BD" /></div>
        <div className="col-md-6 mb-20"><label className="label fs-16 mb-2">Carrier Name</label><input className="form-control" value={data.carrier_name} onChange={(event) => setData('carrier_name', event.target.value)} /></div><div className="col-md-6 mb-20"><label className="label fs-16 mb-2">Subscription ID</label><input className="form-control" value={data.subscription_id} onChange={(event) => setData('subscription_id', event.target.value)} /></div>
        <div className="col-md-12 mb-20"><label className="label fs-16 mb-2">SIM Serial Number</label><input className="form-control" value={data.sim_serial_number} onChange={(event) => setData('sim_serial_number', event.target.value)} /></div>
        <div className="col-md-6 mb-20"><label className="label fs-16 mb-2">Status</label><select className="form-select" value={data.status} onChange={(event) => setData('status', event.target.value)}><option value="active">Active</option><option value="inactive">Inactive</option><option value="no_signal">No Signal</option><option value="disabled">Disabled</option></select></div><div className="col-md-6 mb-20 d-flex align-items-end"><div className="form-check mb-2"><input id="is_enabled" className="form-check-input" type="checkbox" checked={data.is_enabled} onChange={(event) => setData('is_enabled', event.target.checked)} /><label htmlFor="is_enabled" className="form-check-label">Enable SMS sending</label></div></div>
        <div className="col-12"><div className="d-flex gap-2"><button className="btn btn-primary text-white" disabled={processing}>Add SIM</button><Link href="/admin/devices" className="btn btn-secondary">Cancel</Link></div></div>
    </div></form></div></div><div className="col-lg-4"><div className="card bg-white p-20 rounded-10 border border-white mb-4"><h3 className="mb-3">SIM Details</h3><p className="text-muted mb-0">Select a team first, then choose one of its devices. A device can have only one SIM for each slot number.</p></div></div></div></>;
}
