import { Head, Link, router } from '@inertiajs/react';
import { useEffect, useState } from 'react';
import Swal from 'sweetalert2';

export default function Index({ messageTemplates, filters }: any) {
    const [search, setSearch] = useState(filters?.search ?? '');
    useEffect(() => { const timer = setTimeout(() => router.get('/admin/message-templates', { search }, { preserveState: true, replace: true }), 500); return () => clearTimeout(timer); }, [search]);
    const remove = (id: number) => Swal.fire({ title: 'Delete message template?', text: 'This action cannot be undone!', icon: 'warning', showCancelButton: true, confirmButtonColor: '#dc3545', cancelButtonColor: '#6c757d', confirmButtonText: 'Yes, delete template' }).then((result) => result.isConfirmed && router.delete(`/admin/message-templates/${id}`));
    return <><Head title="Message Template List" /><div className="main-content-container overflow-hidden" style={{ minHeight: '75vh' }}><div className="row"><div className="col-md-12"><div className="card bg-white rounded-10 border border-white mb-4">
        <div className="d-flex justify-content-between align-items-center flex-wrap gap-3 p-20"><Link className="bg-transparent text-primary fs-16 border-0 p-0" href="/admin/message-templates/create">+ Add New Template</Link><div className="d-flex align-items-center gap-2 flex-wrap"><input className="form-control" style={{ width: '250px' }} value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search template title" /><button className="btn btn-primary text-white" onClick={() => router.get('/admin/message-templates', { search }, { preserveState: true, replace: true })}>Filter</button><button className="btn btn-secondary" onClick={() => { setSearch(''); router.get('/admin/message-templates'); }}>Reset</button></div></div>
        <div className="default-table-area mx-minus-1 table-to-do-list"><div className="table-responsive"><table className="table align-middle w-100"><thead><tr><th>Template ID</th><th>Title</th><th>Message</th><th>Team</th><th>Creator</th><th>Status</th><th>Created Date</th><th className="text-end">Action</th></tr></thead><tbody>{messageTemplates.data.length ? messageTemplates.data.map((template: any) => <tr key={template.id}><td>#{template.id}</td><td><h4 className="fw-medium fs-16 mb-0">{template.title}</h4><small className="text-muted text-capitalize">{template.template_type}</small></td><td>{template.message.length > 65 ? `${template.message.slice(0, 65)}…` : template.message}</td><td>{template.team?.team_name ?? '—'}</td><td>{template.creator ? `${template.creator.first_name} ${template.creator.last_name}` : '—'}</td><td><span className={`badge ${template.is_active ? 'bg-success' : 'bg-secondary'}`}>{template.is_active ? 'Active' : 'Inactive'}</span></td><td>{new Date(template.created_at).toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' })}</td><td><div className="d-flex justify-content-end" style={{ gap: '12px' }}><Link className="bg-transparent p-0 border-0 hover-text-success" href={`/admin/message-templates/${template.id}`}><i className="material-symbols-outlined fs-16 fw-normal text-body">visibility</i></Link><Link className="bg-transparent p-0 border-0 hover-text-success" href={`/admin/message-templates/${template.id}/edit`}><i className="material-symbols-outlined fs-16 fw-normal text-primary">edit</i></Link><button className="bg-transparent p-0 border-0 hover-text-danger" onClick={() => remove(template.id)}><i className="material-symbols-outlined fs-16 fw-normal text-danger">delete</i></button></div></td></tr>) : <tr><td colSpan={8} className="text-center py-5">No message templates found</td></tr>}</tbody></table></div><div className="d-flex justify-content-between align-items-center flex-wrap gap-3 pt-20 p-20"><span className="fs-14 text-muted">Showing {messageTemplates.data.length} templates</span><ul className="pagination mb-0">{messageTemplates.links?.map((link: any, index: number) => <li key={index} className={`page-item ${link.active ? 'active' : ''} ${!link.url ? 'disabled' : ''}`}><button className="page-link" disabled={!link.url} onClick={() => link.url && router.visit(link.url, { preserveState: true, preserveScroll: true })} dangerouslySetInnerHTML={{ __html: link.label }} /></li>)}</ul></div></div>
    </div></div></div></div></>;
}
