import { Link, useForm } from '@inertiajs/react';
import Select from 'react-select';

export default function CampaignForm({ campaign, teams = [], templates = [], sims = [], contactLists = [] }: any) {
    const { data, setData, post, put, processing, errors } = useForm({ team_id: campaign?.team_id?.toString() ?? '', template_id: campaign?.template_id?.toString() ?? '', sim_id: campaign?.sim_id?.toString() ?? '', campaign_name: campaign?.campaign_name ?? '', description: campaign?.description ?? '', campaign_type: campaign?.campaign_type ?? 'regular', tags: campaign?.tags?.join(', ') ?? '', recipient_list_ids: campaign?.recipient_list_ids ?? [], schedule_type: campaign?.schedule_type ?? 'now', date: campaign?.date ?? '', time: campaign?.time ?? '', timezone: campaign?.timezone ?? 'UTC', is_draft: campaign?.is_draft ?? false, is_active: campaign?.is_active ?? true });
    const selected = (items: any[], value: string, label: (item: any) => string) => { const item = items.find((entry) => String(entry.id) === value); return item ? { value, label: label(item) } : null; };
    const simLabel = (sim: any) => `Slot ${sim.slot_number} — ${sim.phone_number || 'No number'} (${sim.device?.name || 'Unknown device'})`;
    const selectStyles = { control: (base: any) => ({ ...base, minHeight: '45px', borderColor: '#e2e8f0' }) };
    const submit = (event: React.FormEvent) => { event.preventDefault(); campaign ? put(`/admin/campaigns/${campaign.id}`) : post('/admin/campaigns'); };

    return <form onSubmit={submit}><div className="row"><div className="col-lg-8"><div className="card bg-white p-20 rounded-10 border border-white mb-4"><div className="mb-20"><label className="label fs-16 mb-2">Campaign Name</label><input required className="form-control" value={data.campaign_name} onChange={(event) => setData('campaign_name', event.target.value)} placeholder="Enter campaign name" />{errors.campaign_name && <div className="text-danger">{errors.campaign_name}</div>}</div><div className="mb-20"><label className="label fs-16 mb-2">Description</label><textarea className="form-control" rows={5} value={data.description} onChange={(event) => setData('description', event.target.value)} placeholder="Internal campaign notes" /></div><div><label className="label fs-16 mb-2">Tags</label><input className="form-control" value={data.tags} onChange={(event) => setData('tags', event.target.value)} placeholder="promotion, august (comma-separated)" /></div></div></div><div className="col-lg-4"><div className="card bg-white p-20 rounded-10 border border-white mb-4"><h3 className="mb-20">Campaign Setup</h3>
        <div className="mb-20"><label className="label fs-16 mb-2">Team</label><Select isClearable options={teams.map((team: any) => ({ value: String(team.id), label: team.team_name }))} value={selected(teams, data.team_id, (team) => team.team_name)} onChange={(option) => setData('team_id', option?.value ?? '')} placeholder="Select Team" styles={selectStyles} />{errors.team_id && <div className="text-danger">{errors.team_id}</div>}</div>
        <div className="mb-20"><label className="label fs-16 mb-2">Message Template</label><Select isClearable options={templates.map((template: any) => ({ value: String(template.id), label: template.title }))} value={selected(templates, data.template_id, (template) => template.title)} onChange={(option) => setData('template_id', option?.value ?? '')} placeholder="Select Message Template" styles={selectStyles} />{errors.template_id && <div className="text-danger">{errors.template_id}</div>}</div>
        <div className="mb-20"><label className="label fs-16 mb-2">Sending SIM</label><Select isClearable options={sims.map((sim: any) => ({ value: String(sim.id), label: simLabel(sim) }))} value={selected(sims, data.sim_id, simLabel)} onChange={(option) => setData('sim_id', option?.value ?? '')} placeholder="Select Sending SIM" styles={selectStyles} />{errors.sim_id && <div className="text-danger">{errors.sim_id}</div>}</div>
        <div className="mb-20"><label className="label fs-16 mb-2">Recipient Lists</label><Select isMulti options={contactLists.map((list: any) => ({ value: String(list.id), label: list.name }))} value={contactLists.filter((list: any) => data.recipient_list_ids.includes(Number(list.id))).map((list: any) => ({ value: String(list.id), label: list.name }))} onChange={(options) => setData('recipient_list_ids', options.map((option) => Number(option.value)))} placeholder="Select Recipient Lists" styles={selectStyles} />{errors.recipient_list_ids && <div className="text-danger">{errors.recipient_list_ids}</div>}</div>
        <div className="mb-20"><label className="label fs-16 mb-2">Campaign Type</label><Select isSearchable={false} options={[{ value: 'regular', label: 'Regular' }, { value: 'automated', label: 'Automated' }, { value: 'ab_test', label: 'A/B Test' }]} value={{ value: data.campaign_type, label: data.campaign_type === 'ab_test' ? 'A/B Test' : data.campaign_type.charAt(0).toUpperCase() + data.campaign_type.slice(1) }} onChange={(option) => setData('campaign_type', option?.value ?? 'regular')} styles={selectStyles} /></div>
        <div className="mb-20"><label className="label fs-16 mb-2">Schedule</label><Select isSearchable={false} options={[{ value: 'now', label: 'Send now' }, { value: 'later', label: 'Send later' }]} value={{ value: data.schedule_type, label: data.schedule_type === 'later' ? 'Send later' : 'Send now' }} onChange={(option) => setData('schedule_type', option?.value ?? 'now')} styles={selectStyles} /></div>
        {data.schedule_type === 'later' && <><div className="mb-20"><input type="date" className="form-control" value={data.date} onChange={(event) => setData('date', event.target.value)} /></div><div className="mb-20"><input type="time" className="form-control" value={data.time} onChange={(event) => setData('time', event.target.value)} /></div></>}
        <div className="form-check mb-2"><input id="draft" className="form-check-input" type="checkbox" checked={data.is_draft} onChange={(event) => setData('is_draft', event.target.checked)} /><label htmlFor="draft" className="form-check-label">Save as draft</label></div><div className="form-check mb-20"><input id="active" className="form-check-input" type="checkbox" checked={data.is_active} onChange={(event) => setData('is_active', event.target.checked)} /><label htmlFor="active" className="form-check-label">Active campaign</label></div><div className="d-flex gap-2"><button className="btn btn-primary text-white" disabled={processing}>{campaign ? 'Update Campaign' : 'Create Campaign'}</button><Link href="/admin/campaigns" className="btn btn-secondary">Cancel</Link></div>
    </div></div></div></form>;
}
