import { Head, Link } from '@inertiajs/react';

export default function Show({ campaign }: any) {
    const simLabel = campaign.sim
        ? `Slot ${campaign.sim.slot_number} — ${campaign.sim.phone_number || 'No number'} (${campaign.sim.device?.name || 'Unknown device'})`
        : '—';

    return <><Head title={campaign.campaign_name || 'Campaign'} /><div className="row"><div className="col-lg-4"><div className="card bg-white p-20 rounded-10 border border-white"><div className="text-center"><div className="rounded-circle bg-primary text-white d-inline-flex align-items-center justify-content-center mb-3" style={{width: 80, height: 80}}><i className="material-symbols-outlined fs-36">sms</i></div><h3>{campaign.campaign_name || 'Unnamed Campaign'}</h3><span className={`badge ${campaign.is_draft ? 'bg-warning text-dark' : campaign.is_active ? 'bg-success' : 'bg-secondary'}`}>{campaign.is_draft ? 'Draft' : campaign.is_active ? 'Active' : 'Inactive'}</span></div><hr /><p><strong>Team:</strong> {campaign.team?.team_name || '—'}</p><p><strong>Type:</strong> <span className="text-capitalize">{campaign.campaign_type.replace('_', ' ')}</span></p><p><strong>Schedule:</strong> {campaign.schedule_type === 'later' ? `${campaign.date || ''} ${campaign.time || ''} (${campaign.timezone || 'UTC'})` : 'Send now'}</p></div></div><div className="col-lg-8"><div className="card bg-white p-20 rounded-10 border border-white"><div className="d-flex justify-content-between align-items-center mb-20"><h3 className="mb-0">SMS Campaign Details</h3><div className="d-flex gap-2"><Link href={`/admin/campaigns/${campaign.id}/edit`} className="btn btn-primary text-white">Edit</Link><Link href="/admin/campaigns" className="btn btn-secondary">Back</Link></div></div><div className="row"><div className="col-md-6 mb-4"><label className="label fs-14 text-muted mb-2">Message Template</label><div className="form-control bg-light">{campaign.template?.title || '—'}</div></div><div className="col-md-6 mb-4"><label className="label fs-14 text-muted mb-2">Sending SIM</label><div className="form-control bg-light">{simLabel}</div></div><div className="col-md-12 mb-4"><label className="label fs-14 text-muted mb-2">Recipient Lists</label><div className="form-control bg-light">{campaign.recipient_lists?.length ? campaign.recipient_lists.map((list: any) => list.name).join(', ') : '—'}</div></div><div className="col-md-12 mb-4"><label className="label fs-14 text-muted mb-2">Description</label><div className="form-control bg-light" style={{minHeight: '100px', whiteSpace: 'pre-wrap'}}>{campaign.description || '—'}</div></div>{campaign.tags?.length > 0 && <div className="col-md-12"><label className="label fs-14 text-muted mb-2">Tags</label><div className="d-flex gap-2 flex-wrap">{campaign.tags.map((tag: string) => <span key={tag} className="badge bg-info">{tag}</span>)}</div></div>}</div></div></div></div></>;
}
